version: '2'
services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
    links:
      - beanstalkd
      - mysql
      - redis
    environment:
      - LARAVEL_ENV=local
      - REDIS_HOST=redis
      - BEANSTALKD_HOST=beanstalkd

  beanstalkd:
    image: chriskite/beanstalkd
    ports:
      - "11300:11300"

  mysql:
    build: mysql
    volumes:
      - ./mysql/data:/var/lib/data
    ports:
      - "3306:3306"
    env_file: ./app/.env

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
